### ISSUE TITLE
Handle all possible Openfaas errors

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#10]
- [x] https://github.com/lenra-io/server/issues/58
- [x] https://github.com/lenra-io/application-runner/issues/55
- [x] https://github.com/lenra-io/client/issues/49
- [x] https://github.com/lenra-io/dev-tools/issues/45
