### ISSUE TITLE
Manage app access

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/Lenra#11]
We want to be able to manage user access to an application. An application can be private with invitations or public for everyone to use.

An email should be sent to the invited user.

- [x] https://github.com/lenra-io/server/issues/63
- [x] https://github.com/lenra-io/client/issues/53 
- [x] https://github.com/lenra-io/server/issues/64
- [x] https://github.com/lenra-io/server/issues/66
- [x] https://github.com/lenra-io/server/issues/65
- [x] https://github.com/lenra-io/client/issues/64
- [x] lenra-io/client#146

**Comment by Nesqwik** [comment]
@jonas-martinez
