### ISSUE TITLE
[EPIC] Data transition, Postgres to Mongo

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#117]
# Postgres to Mongo

all the above discussions lead to one doc, which can be found here https://github.com/lenra-io/application-runner/pull/184
all work concerning mongo will be done in this PR

### Rework of Environment Manager
- [x] https://github.com/lenra-io/application-runner/issues/185
- [x] https://github.com/lenra-io/application-runner/issues/186
- [x] https://github.com/lenra-io/application-runner/issues/187

### Rework of Session Manager
- [x] https://github.com/lenra-io/application-runner/issues/188
- [x] https://github.com/lenra-io/application-runner/issues/190
- [x] https://github.com/lenra-io/application-runner/issues/191
- [x] https://github.com/lenra-io/application-runner/issues/192

### Widget
- [x] https://github.com/lenra-io/application-runner/issues/189 
- [x] https://github.com/lenra-io/application-runner/issues/193

### Query
- [x] https://github.com/lenra-io/application-runner/issues/194
- [x] https://github.com/lenra-io/application-runner/issues/195

### Mongo
- [x] https://github.com/lenra-io/application-runner/issues/196
- [x] https://github.com/lenra-io/application-runner/issues/197
- [x] https://github.com/lenra-io/application-runner/issues/207

### Mongo Session
- [x] https://github.com/lenra-io/application-runner/issues/198
- [x] https://github.com/lenra-io/application-runner/issues/199

### Mongo Transaction
- [ ] https://github.com/lenra-io/application-runner/issues/200
- [x] https://github.com/lenra-io/application-runner/issues/201

#
# old discussion

# How to transition the data sytem from Postgres to Mongo

This epic will describe the steps to move from the current Data system using Postgres to the Mongodb equivalent.

## The choice : 
I have explored mongodb more and i discover a few useful features.
- Mongo have a "change stream" feature that allow to get realtime changed from a collection and filter them using a query.
- Mongo do have transactions (like postgres)
- The query system of mongo is a JSON object

This means that if we use mongo change stream and the json query of mongo. This fix two of our major issue we currently have using postgres.

**The drawback are :** 
- The dev data are separated from the user data in postgres. We need to recreate a certain link between them.
- The relations are virtually gone. We cannot create strong relations between rows like postgres do. 
- The types and constraints are weaker. We can still use BSON schema tho.
- This adds another database that must be managed more complexe stack.

## Mongo architecture choice
We have basically two choice regarding the connexion between mongo and the dev App : 
- The app handle the mongo driver and database directly. 
- The app send HTTP request to the server and the server transfer these query to mongo

|                          	| Direct connexion                               	| Server act as gateway                                               	|
|--------------------------	|------------------------------------------------	|---------------------------------------------------------------------	|
| Connexion type           	| APP > TCP > Mongo                              	| APP > HTTP > Server > TCP > Mongo                                   	|
| Driver dependant         	| YES some languages do not<br>have a driver     	| NO                                                                  	|
| Mongo version management 	| Driver must be compatible<br>Harder to migrate 	| Single version<br>Easier to migrate                                 	|
| Performances             	| Probably better                                	| Probably worse but potentially <br>better connexion pool management 	|
| Config for the devs      	| Higher (need a driver, config etc..)           	| almost none                                                         	|
| Complexity/maintenance   	| Less complexity for us                         	| More complexity/maintenance                                         	|
| Feature Compatibility    	| All that the driver handle                     	| Only what we allow via the HTTP API                                 	|
| Transactions             	| Compatible (if driver does it)                 	| Might not be compatible                                             	|

Since lenra wants to simplify the app development, we choose to use the Server as a gateway.

## What needs to be done 

Here are all the steps to change the data system : 
- [Devops] Host a mongo instance and allow to dynamically create new databases/instances
- [Devops] Long term : Scale the mongo instance using shards
- [Devops] Enable the replica set protocol to use the changestream
- [ApplicationRunner] Implement the "ReatimeQueryGenserver" to listen a query and get changes realtime.
- [ApplicationRunner] Implement a "WidgetGenserver" that can connect to a "ReatimeQueryGenserver" and update the data change.
- [ApplicationRunner] Change the Session to ask the UI of the "WidgetGenserver" when they are rebuilding the UI.
- [ApplicationRunner] Make the "WidgetGenserver" notify the sessions that they changed so they can rebuild
- [ApplicationRunner] Change the API to match the mongo equivalent (insert, insertAll, update, create collection...)

## Mongo implementation for ApplicationRunner
Since Applicationrunner refactor all the jobs for implement mongo are now all in applicationRunner.
First step of the implementation is to create an new repository module that connect to a mongodb database using mongo driver (see https://github.com/zookzook/elixir-mongodb-driver).

Some specification:

- We will have one database per environment, each environment will start a new repo at startup.
- For each listeners request we will start a new mongo session.
- For each session, listeners can start transaction and add many action in this transaction.

Architecture of GenServer:

```mermaid
graph
     E --> MTDS
     E --> QDS
     E --> Repo
     E --> MSDS
     E --> WDS
     S --> QSD
QSD --> CS
WDS --> W
MSDS --> MS
QDS --> Q
MTDS --> MT
```
with:

- E & S, Environment and Session
- QDS: Query dynamic supervisor, which starts Q, Q will be placed in the swarm group by the session.
- Q: Query, which listens to the swarm messages sent by QSD and notifies W if the data has changed.
- WDS: Dynamic widget supervisor, starts the widget.
- W: Widget, cache the widget interface, and listen to Q to rebuild if necessary.
- MSDS: Dynamic Mongo Session Supervisor, start the Mongo session
- MS: Mongo Session, a session is started for each listener and stops when the listeners end.
- MTDS : Mongo dynamix transaction supervisor
- MT: Mongo Transaction, started by a request from the application and linked to a mongo session. 

## Notes about the ReatimeQueryGenserver
We should use this driver : https://hexdocs.pm/mongodb_driver/0.9.1/readme.html

** THIS SOLUTION IS NOT POSSIBLE DUE TO MONGO LIMITATIONS ABOUT CHANGE STREAMS **
```
This genserver is spawn under a Dynamic supervisor. It is in charge of listening a query and update the data associated.
To do that it will use the ChangeStream API.

The ChangeStream allow us to listen ALL the changed from a collection. We are then connected to the event stream that list all the changed made to the collection.
The event changes can be a DELETE, UPDATE or INSERT change. It contains all the changes made to the base item and we can add the `fullDocument` option to get the document that have been changed for every event (except delete).
We can filter these event using the aggregate function.

I have described the idea of this module in a gist : 
https://gist.github.com/Nesqwik/d92e3158de87b87855122ef74983629b
```

We must drastically reduce the number of ChangeStream connexion because of the connexion limitations on mongo db.
The solution is to create a single changeStream for the whole Database. These events will be sent to the `RealtimeQueryGenserver` where our implementation of a subset of mongo query will filter and update the local data for us.
