### ISSUE TITLE
[EPIC] Generate and publish client doc to Github Pages

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/Lenra#121]
## Client side documentation

- [x] https://github.com/lenra-io/Lenra/issues/124

### Documentation generation + deployment to Github Pages

- [x] https://github.com/lenra-io/client-store/pull/19
- [x] https://github.com/lenra-io/client-backoffice/pull/31
- [x] https://github.com/lenra-io/client-common/pull/39
- [x] https://github.com/lenra-io/client-app/pull/27
- [x] https://github.com/lenra-io/lenra_components/pull/112
- [x] https://github.com/lenra-io/lenra_ui_runner/pull/169

**Comment by jonas-martinez** [comment]
# How to handle doc generation and versioning

To properly handle the doc generation and versioning there is multiple aspects that we need to make sure are working properly.
- The documentation should have versioning, this means that we must keep track old versions of the documentation while making sure that we are not polluting the host repository. Links to older versions should be added, we could use a dropdown just like the hexdocs : https://hexdocs.pm/elixir/1.12/Kernel.html
- The documentation should be put in a specific branch in the host repository or in a new repository if it brings too much complexity. This will ensure that the documentation does not pollute the host repository code and we could create specific github actions for the documentation.

Some Github Actions listed in the **sources** below could be used to make this work easier

@lenra-io/devs What do you think ? Is there anything to add ?


**sources**
https://github.com/JamesIves/github-pages-deploy-action
https://glebbahmutov.com/blog/versioned-doc-pages/

**Comment by jonas-martinez** [comment]
It seems to be quite hard to handle versioning of documentation using github pages. We cannot reference a tag or commit in the URL of the github page and see old changes. We would need to store all versions of the documentation in the latest commit and that could become really heavy real fast.

htmlpreview.github.io could be a nice alternative.

**Comment by taorepoara** [comment]
Yes it might be interesting

**Comment by Nesqwik** [comment]
If i understand correctly, github-pages have its own repo next to the main repo.

Each PR merged in the main repo have it's own updated doc and trigger a new version release.
This release also release the doc under a new branch on the github-page repo.
- The "main" branch of the github-page repo contain the latest doc.
- The "beta" branch of the github-pages repo contain the current beta doc
- The "vx.x.x" branch of the github-pages repo contain the specific branch version.

The docs are accessible from the urls : 
https://lenra-server.gh-pages.io/main/index.html
https://lenra-server.gh-pages.io/beta/index.html
https://lenra-server.gh-pages.io/vx.x.x/index.html

We then simply have to change the url to access an other version of the doc.
I don't know if it's possible but it could be the most simple option.

**Comment by jonas-martinez** [comment]
@Nesqwik It is unfortunately not possible to target a specific ref/branch with Github Pages, it will always take the latest published version of the doc.

**Comment by jonas-martinez** [comment]
What @taorepoara meant is that we could use the Github Pages for the latest version of the doc and use the `htmlpreview` to access older versions

**Comment by Nesqwik** [comment]
Then could we simply deploy our doc branch to a different directory in github pages ?

**Comment by Nesqwik** [comment]
Whatever the solution, we can simply setup gh-pages first without the versionning and add it later :)
