### ISSUE TITLE
[EPIC] Make client repositories public

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/Lenra#124]
We should make every client repositories public based on the following discussion : https://github.com/lenra-io/Lenra/discussions/116

GPL License must be used.

- [x] lenra-io/client-backoffice#33
- [x] https://github.com/lenra-io/client-store/issues/13
- [x] https://github.com/lenra-io/client-app/issues/20
- [x] https://github.com/lenra-io/client-common/issues/31
- [x] https://github.com/lenra-io/lenra_components/issues/110
- [x] https://github.com/lenra-io/lenra_ui_runner/issues/164

Add alpha release for each repository

- [x] client-backoffice alpha release
- [x] client-store alpha release
- [x] client-app alpha release
- [x] client-common alpha release
- [x] lenra_components alpha release
- [x] lenra_ui_runner alpha release

After resolving all of these issues, we can make all of the client repositories public.
