### ISSUE TITLE
[Epic] Lenra CLI - init

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/Lenra#129]
### Discussed in https://github.com/lenra-io/Lenra/discussions/123

<div type='discussions-op-text'>

<sup>Originally posted by **taorepoara** July 27, 2022</sup></div>

Here is first list of commands managed by the CLI:

- [x] https://github.com/lenra-io/lenra_cli/issues/1
- [x] https://github.com/lenra-io/lenra_cli/issues/2
- [x] https://github.com/lenra-io/lenra_cli/issues/3
