### ISSUE TITLE
[Epic] Change doc website domain to docs.lenra.io

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/Lenra#131]
Change the doc website domain to `docs.lenra.io` and all the references.

- [x] Change the deployment configuration
- [x] Set the domain in the DNS
- [x] https://github.com/lenra-io/website/pull/38
- [x] https://github.com/lenra-io/client-backoffice/pull/36
- [x] Create a redirection from doc.lenra.io to docs.lenra.io

**Comment by taorepoara** [comment]
@shiipou @jonas-martinez @Thibault5 Can you handle this epic please ?

**Comment by shiipou** [comment]
Ok I'll do it tomorrow.
