### ISSUE TITLE
Add app access field in app settings

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#14]
We must be able to define the application environments visibility from the UI. It should be possible to switch between public or private for each environment.

If the application environment is private, it must be possible to invite users to join it.

### This work will be divided like this:

- [x] https://github.com/lenra-io/client/issues/61
- [x] https://github.com/lenra-io/client/issues/62 
- [x] https://github.com/lenra-io/client/issues/63 
- [x] https://github.com/lenra-io/client/issues/64

**Comment by Nesqwik** [comment]
https://www.figma.com/file/lZuzdHNwRoWqVhev6TQKE2/Project-%2F-Settings?node-id=422%3A1415
