### ISSUE TITLE
Translate the client

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#21]
- [x] https://github.com/lenra-io/client/pull/92
- [x] https://github.com/lenra-io/client/pull/93
- [x] https://github.com/lenra-io/client/pull/94
- [x] https://github.com/lenra-io/client/pull/95
- [x] https://github.com/lenra-io/client/pull/96
- [x] https://github.com/lenra-io/client/pull/97
- [x] https://github.com/lenra-io/client/pull/98
- [x] https://github.com/lenra-io/client/pull/99
- [x] https://github.com/lenra-io/client/pull/100
- [x] https://github.com/lenra-io/client/pull/101
- [x] https://github.com/lenra-io/client/pull/102
- [x] https://github.com/lenra-io/client/pull/103
- [x] https://github.com/lenra-io/client/pull/104
- [x] https://github.com/lenra-io/client/pull/105
- [x] https://github.com/lenra-io/client/pull/106
- [x] https://github.com/lenra-io/client/pull/108
- [x] https://github.com/lenra-io/client/pull/109
