### ISSUE TITLE
Landing page rework

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#24]
Landing page rework for the beta test version:

- [x] https://github.com/lenra-io/website/issues/4
- [x] https://github.com/lenra-io/website/issues/5
- [x] https://github.com/lenra-io/website/issues/6
- [x] https://github.com/lenra-io/website/issues/7
- [x] https://github.com/lenra-io/website/issues/8
- [x] https://github.com/lenra-io/website/issues/9
- [x] https://github.com/lenra-io/website/issues/10
- [x] https://github.com/lenra-io/website/issues/12
- [x] https://github.com/lenra-io/website/issues/13

**Comment by jonas-martinez** [comment]
@taorepoara
