### ISSUE TITLE
Adding context usage in an app

### ISSUE THREAD

**Issue by ClementGld** [lenra-io/Lenra#25]
We want to use a context in any app who want this : 

Client:

- [x] https://github.com/lenra-io/client/issues/124
- [x] https://github.com/lenra-io/client/issues/125

Server:

- [x] https://github.com/lenra-io/server/issues/194

**All issue below have to wait the new system of data, to be implement**

- [x] https://github.com/lenra-io/server/issues/195

Application_runner:

- [x] https://github.com/lenra-io/application-runner/issues/135

Component-api:
- [x] https://github.com/lenra-io/components-api/issues/112

In the end after the context work with only 1 parameters, we have to add more parameters.

- [x] https://github.com/lenra-io/client/issues/126

**Comment by ClementGld** [comment]
actually we have some PR here : 

- https://github.com/lenra-io/application-runner/pull/159/files
- https://github.com/lenra-io/dev-tools/pull/116
- https://github.com/lenra-io/templates/pull/66
- https://github.com/lenra-io/client/pull/176
- https://github.com/lenra-io/server/pull/226

**Comment by Nesqwik** [comment]
@ClementGld If the PR are related to the issue above, you don't have to link them into the epic :) 
Just connect the PR with te related issue, and when the PR is closed/validated, the issue should be closed too.
