### ISSUE TITLE
[EPIC] Better Error handling

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#53]
The goal of this epic is to define and implement a better error handling system.
Some questions need to be answered.

Server side : 
- When do we want to return :error tuple, raise and/or Logger.error ?
- How do we handle the stacktrace and Logger.error logs (store in db ? In file ? Add metadata to it ?)
- What is the form of the :error tuple ?
- How do we send the error to the client when using API ? When using Websocket ?

Client side : 
- How do we print errors to the users on form ? on App ? 
- Which kind of error do we want to print ? Technical ? more user-friendly ?
- How do we react to a specific error to adjust the UI ?

We must document our choices and implement them.

The repository that are affected (this will change after the repository reorganisation) : 
- https://github.com/lenra-io/server
- https://github.com/lenra-io/dev-tools
- https://github.com/lenra-io/application-runner
- https://github.com/lenra-io/client

### Tasks

|        |  App |              API             |                    Client                    |
|:------:|:----:|:----------------------------:|:--------------------------------------------:|
| Business |  dev | Returns an error (400 range) |                       X                      |
|  Tech  |  dev |     500 error + DB / File    | Generic handling,  component-level display |
|   Dev  | Client error + Notify Dev + Callback + Server error |      500 error + Sentry      |      Generic display + Sentry + GDPR     |

#### client-store
- [x] lenra-io/client-store#10

#### client-backoffice
- [x] lenra-io/client-backoffice#18

#### Server part
- [x] https://github.com/lenra-io/server/issues/258
