### ISSUE TITLE
[EPIC] Self-hosted Plausible

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#54]
We want to [self-host plausible](https://plausible.io/self-hosted-web-analytics). 
This plausible instance must be protected and only accessible from Lenra workforce.

- [x] https://github.com/lenra-io/kubernetes/issues/51
- [x] Prevent registering on self-hosted plausible
- [x] Remove the staging analytics deployment
- [x] Add the intra-login filter except for the event API

**Comment by Nesqwik** [comment]
@shiipou you can check the above and close the epic when everything is done and merged !
