### ISSUE TITLE
[EPIC] Repository reorganization 

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#55]
Some of our repository are too monolytics and could be split for better reuse as dependancies.

For the client, we currenlty have only one repository that host the "Store" part and the "backoffice" part. Some view and logic are share between them : the auth system. 
The devtool currently import the whole client just to print the developper app.

We can then have : 
- The `App` repository that only handle how the "LenraUI" apps are build/shown, and how to connect with them (websocket). 
- The `Auth` repository that handle the login system and views.
- The future `Store` repository will handle the Home page of a Lenra user that show the latest app etc.. It uses `Auth` and `App` as dependancies.
- The `Backoffice` repository that handle de developper dashboard. It uses the `Auth` as dependancy.
- The `Devtool` now can only use the `App` repository as dependancy to show the app.

For the server, we currently have the "Server" and "Devtool" repository that duplicate a good amount of code relative to the application system. 
We can refactor the repo like that : 
- The `Data` repo that handle the data logic (parsing from json to AST, from AST to ecto, validator etc..)
- The `application_runner` repository that will be an almost autonomous repo. It will handle the Data API, database migration around the Data system, the websocket connexion and UI validation to run a Lenra app. It will use the `Data` repo as dependancy.
- The `Devtool` will handle the devtool server and use `application_runner` as dependancy.
- The `Server` will handle the other general API and the Auth API and will use `application_runner` as dependancy.

### Server part

- [X] https://github.com/lenra-io/query-parser/issues/3
- [X] https://github.com/lenra-io/query-parser/issues/4
- [x] https://github.com/lenra-io/query-parser/issues/5
- [x] https://github.com/lenra-io/application-runner/issues/158
- [x] https://github.com/lenra-io/server/issues/250

##### `Store` repository
- [x] Create Store repository

##### `Common Repository`
- [x] Create `client-common` repository
- [x] lenra-io/client-common#1
- [x] Add Models
- [x] Add API boilerplate (errors, HTTPClient, ...)
- [x] Add Error boilerplate (snackbar, error_page)
- [x] Add Page boilerplate (simple_page, ...)
- [x] Add tests for API
- [x] lenra-io/client-common#6
- [x] lenra-io/client-common#9
- [x] lenra-io/client-common#10

##### `App` Repository
- [x] Create `App` repository (Can be current `client` repository renamed and refactored according to the changes in this epic)

##### `Backoffice` Repository
- [x] lenra-io/client-backoffice#1
- [x] lenra-io/client-backoffice#2
- [x] lenra-io/client-backoffice#3
- [x] lenra-io/client-backoffice#4
- [x] lenra-io/client-backoffice#5

##### `Devtool` Repository
- [x] Change dependencies

##### Handle versioning in each of above mentioned repository
- [x] lenra-io/client-common#24
- [x] lenra-io/client-app#13
- [x] Handle versioning in `client-backoffice`
- [x] Handle versioning in `client-store`
- [x] Handle versioning in devtools client

**Comment by pichoemr** [comment]
for server part:

- [X] https://github.com/lenra-io/query-parser/issues/3
- [X] https://github.com/lenra-io/query-parser/issues/4
- [ ] https://github.com/lenra-io/query-parser/issues/5
- [ ] https://github.com/lenra-io/application-runner/issues/158
- [ ] https://github.com/lenra-io/server/issues/250

**Comment by taorepoara** [comment]
Is the devtool style having client and server in the same repo ?

**Comment by jonas-martinez** [comment]
> Is the devtool style having client and server in the same repo ?

@taorepoara Yes the devtool repository will remain as it is now (client and server).

**Comment by jonas-martinez** [comment]
@Nesqwik All of the client side work should be finished now. 
I still need to make sure that every repository is using the new ones and we will have the possibility to remove the current `client` repository in the future.

**Comment by jonas-martinez** [comment]
Some README documentation might be necessary, but it can be incrementally done along with other features.
