### ISSUE TITLE
[EPIC] Application runner code refactor

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#56]
After The repository organisation (https://github.com/lenra-io/Lenra/issues/55) for the server, we can refactor the application runner code : 
- Keep all Database migration around the Data in this repository
- Create a Repo that can interact directly with the database.
- Create the Services and Controller to handle the Data system.
- Create the API routes and auth system to allow apps to interact with the API

The goal is that the `application_runner` repo is autonomous to run an application.

### ApplicationRunner jobs:
- [x] https://github.com/lenra-io/application-runner/issues/164
- [x] https://github.com/lenra-io/application-runner/issues/161
- [x] https://github.com/lenra-io/application-runner/issues/163
- [x] https://github.com/lenra-io/application-runner/issues/162
- [x] https://github.com/lenra-io/application-runner/issues/165
- [x] Session & Environment refactor

### Server jobs:
- [x] https://github.com/lenra-io/server/issues/253
- [x] https://github.com/lenra-io/server/issues/254

### DevTools jobs:

- [x] https://github.com/lenra-io/dev-tools/issues/118
- [x] https://github.com/lenra-io/dev-tools/issues/119

**Comment by jonas-martinez** [comment]
@pichoemr What is the state of this EPIC ?
