### ISSUE TITLE
Widget System

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#8]
The Widget system allow the dev to organise the code into multiple widget that can be called with specific data.
The server should be able to handle this new logic from the App, validate the new UI with the widgets and send it to the client.
The client should be able to parse and print these widgets.

- [ ] https://github.com/lenra-io/lenra_ui_runner/issues/112
- [x] https://github.com/lenra-io/application-runner/issues/36
- [x] https://github.com/lenra-io/application-runner/issues/40
- [x] https://github.com/lenra-io/application-runner/issues/41
- [x] https://github.com/lenra-io/templates/pull/21
- [x] https://github.com/lenra-io/server/pull/27
