### ISSUE TITLE
New data system

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#9]
Archives :
- [x] ~https://github.com/lenra-io/server/issues/22~
- [x] ~https://github.com/lenra-io/server/issues/23~
- [x] ~https://github.com/lenra-io/application-runner/issues/43~
- [x] ~https://github.com/lenra-io/application-runner/issues/67~
- [x] ~lenra-io/application-runner#68~
- [x] ~https://github.com/lenra-io/server/issues/103~
- [x] ~https://github.com/lenra-io/application-runner/issues/60~
- [x] ~https://github.com/lenra-io/application-runner/issues/71~
- [x] ~https://github.com/lenra-io/application-runner/issues/72~
- [x] ~https://github.com/lenra-io/server/issues/102~

Doc : 
- [x] https://github.com/lenra-io/application-runner/issues/59

New list:
- [x] https://github.com/lenra-io/application-runner/issues/37
- [x] lenra-io/application-runner#65
- [x] https://github.com/lenra-io/application-runner/issues/83
- [x] https://github.com/lenra-io/application-runner/issues/69
- [x] https://github.com/lenra-io/application-runner/issues/70
- [x] https://github.com/lenra-io/application-runner/issues/90
- [x] https://github.com/lenra-io/application-runner/issues/91
- [x] https://github.com/lenra-io/application-runner/issues/92
- [x] https://github.com/lenra-io/application-runner/issues/93
- [x] https://github.com/lenra-io/application-runner/issues/94
- [x] https://github.com/lenra-io/application-runner/issues/95
- [x] https://github.com/lenra-io/application-runner/issues/73
- [x] https://github.com/lenra-io/application-runner/issues/112
- [x] https://github.com/lenra-io/application-runner/issues/113
- [x] https://github.com/lenra-io/server/issues/114
- [x] https://github.com/lenra-io/server/issues/68
- [x] https://github.com/lenra-io/application-runner/issues/75
- [x] https://github.com/lenra-io/server/issues/160
- [x] https://github.com/lenra-io/server/issues/161
- [x] https://github.com/lenra-io/server/issues/162
- [x] https://github.com/lenra-io/server/issues/163
- [x] https://github.com/lenra-io/server/issues/164
- [x] https://github.com/lenra-io/server/issues/165
- [x] https://github.com/lenra-io/server/issues/166
- [x] https://github.com/lenra-io/server/issues/167
- [x] https://github.com/lenra-io/server/issues/169
- [x] https://github.com/lenra-io/application-runner/issues/74
- [x] https://github.com/lenra-io/server/issues/180
- [x] https://github.com/lenra-io/server/issues/182
- [x] https://github.com/lenra-io/server/issues/181
- [x] https://github.com/lenra-io/application-runner/issues/126
- [x] https://github.com/lenra-io/template-hello-world-node12/issues/13
- [x] https://github.com/lenra-io/application-runner/issues/59
- [x] https://github.com/lenra-io/application-runner/issues/76
- [x] https://github.com/lenra-io/application-runner/issues/77
- [x] https://github.com/lenra-io/application-runner/issues/78
- [x] https://github.com/lenra-io/application-runner/issues/79
- [x] https://github.com/lenra-io/application-runner/issues/80
- [x] https://github.com/lenra-io/application-runner/issues/81
- [x] https://github.com/lenra-io/server/issues/115
- [x] https://github.com/lenra-io/components-api/issues/106

DevTool:

- [x] https://github.com/lenra-io/dev-tools/issues/82
- [x] https://github.com/lenra-io/dev-tools/issues/83
- [x] https://github.com/lenra-io/dev-tools/issues/84
- [x] https://github.com/lenra-io/dev-tools/issues/85
- [x] https://github.com/lenra-io/dev-tools/issues/86
- [x] https://github.com/lenra-io/dev-tools/issues/87
- [x] https://github.com/lenra-io/dev-tools/issues/88
- [x] https://github.com/lenra-io/dev-tools/issues/89

**Comment by shiipou** [comment]
@Nesqwik done for now, probably more will came into this after the #8 will be closed.
