### ISSUE TITLE
[EPIC] Data query system equivalent to mongo

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#90]
Update the data query system to match [the specs](https://github.com/lenra-io/query-parser/tree/beta/docs#readme).

- [ ] Update the Json Schema validator
- [ ] Update the Parser from Json to the "Abstract Syntaxe Tree".
- [ ] Update the Parser from AST to Ecto query.
- [ ] Technical documentation of the Query system
- [ ] Dev documentation of the Query system with examples.
