### ISSUE TITLE
[EPIC] Devtool logs system

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/Lenra#91]
About the Devtool logs that the developper can see, we want to clean the console logs to have a better understanding of what is happening.
So can do the following :
- [ ] Write the Devtools technical logs in a separate file in the docker container
- [ ] Write the `stderr` output of the watchdog into the console (to be confirmed)
- [ ] Log into the console all the listener/widget/manifest/resources calls

**Comment by jonas-martinez** [comment]
Solved by lenra_cli
